# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kosgrey <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/07 15:55:56 by kosgrey           #+#    #+#              #
#    Updated: 2019/09/07 16:01:31 by kosgrey          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRCS = srcs/*.c

all:
		gcc $(SRCS) -o $(NAME)

clean:
		/bin/rm -f *.o

fclean : clean
		/bin/rm -f $(NAME)

re: fclean re
